name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: slacgismo/gridlabd:latest

    steps:
    - uses: actions/checkout@v2
    - name: Get test files
      run: |
        git submodule sync
        git submodule update --init --recursive
    - name: Validation
      run: make validate LIMIT='timeout 60s' || tar czf validate.tar.gz test
    - name: Save results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: validate-result
        path: |
          validate.txt
          validate.tar.gz
      
      - name: Get NSRDB credentials
      env:
        NSRDB_CREDENTIAL: ${{ secrets.NSRDB_CREDENTIAL  }}
      run: |
        mkdir -p $HOME/.nsrdb
        echo $NSRDB_CREDENTIAL > $HOME/.nsrdb/credentials.json

    - name: Cache weather file
      id: weather
      uses: actions/cache@v3
      with:
        path: weather@9q8vq2.csv
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('weather@9q8vq2.csv') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
